//
//  HistoryInteractor.swift
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryBusinessLogic {
    func fetchHistory()
}

protocol HistoryDataStore {
    //var selectedAuthor: Author? { get set }
}

class HistoryInteractor: HistoryBusinessLogic, HistoryDataStore {

    // MARK: Object lifecycle
    
    init() {
    }

    // MARK: Fetch data
  
    func fetchHistory() {
        //performRequest(page: page, authorsPerPage: authorsFirstPage)
    }
    
    private func performRequest(page: Int, authorsPerPage: Int?) {
//        worker.requestAuthors(page: page, authorsPerPage: authorsPerPage) { [weak self] authors, error in
//            if let _error = error {
//                self?.presenter?.presentError(_error)
//                return
//            }
//            guard let authors = authors else { return }
//            self?.presenter?.presentAuthors(authors)
//        }
    }
}
