//
//  HistoryRouter.swift
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryRoutingLogic {
    func routeToAuthorDetails()
}

protocol HistoryDataPassing {
    var dataStore: HistoryDataStore? { get }
}

class HistoryRouter: HistoryRoutingLogic, HistoryDataPassing {
    weak var viewController: HistoryViewController?
    var dataStore: HistoryDataStore?

    init(dataStore: HistoryDataStore?) {
        self.dataStore = dataStore
    }
 
    // MARK: Routing
    
    func routeToAuthorDetails() {
//        let destinationVC = authorDetailsBuilder.build(imageCache: imageCache)
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation
    
//    func navigateToSomewhere(source: HistoryViewController, destination: AuthorDetailsViewController) {
//        source.show(destination, sender: nil)
//    }
//
//    // MARK: Passing data
//
//    func passDataToSomewhere(source: HistoryDataStore, destination: inout AuthorDetailsDataStore) {
//        destination.author = source.selectedAuthor
//    }
}
